# Log in the first time run run_kubernetes.sh
trinhnt@trinhntubt:~/WorkSpace/Study/DevOps/Udacity/Project4/DevOps_Udacity_Project4_Microservice(main)$ ./run_kubernetes.sh 
pod/ml-api created
NAME     READY   STATUS              RESTARTS   AGE
ml-api   0/1     ContainerCreating   0          0s
error: unable to forward port because pod is not running. Current status=Pending

# Log in the second time run run_kubernetes.sh
trinhnt@trinhntubt:~/WorkSpace/Study/DevOps/Udacity/Project4/DevOps_Udacity_Project4_Microservice(main)$ ./run_kubernetes.sh 
Error from server (AlreadyExists): pods "ml-api" already exists
NAME     READY   STATUS    RESTARTS   AGE
ml-api   1/1     Running   0          70s
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80

# Log from Kubernetes
trinhnt@trinhntubt:~/WorkSpace/Study/DevOps/Udacity/Project4/DevOps_Udacity_Project4_Microservice(main)$ kubectl logs ml-api
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 198-445-719
[2023-05-21 11:20:27,272] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2023-05-21 11:20:27,283] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-05-21 11:20:27,292] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-05-21 11:20:27,295] INFO in app: output prediction: 
[20.35373177134412]
127.0.0.1 - - [21/May/2023 11:20:27] "POST /predict HTTP/1.1" 200 -

